### ISSUE TITLE
Failed to build demo_linux

### ISSUE THREAD

**Issue by andrewtholt** [marcinbor85/microshell#4]
Here's what I did
After adding 

```
cmake_minimum_required(VERSION 3.20)    
project(MicroShell) 
```
To CMakeLists.txt to top cmake moaning.

```
mkdir build 
cd build
cmake ..

CMake Error at CMakeLists.txt:7 (build_ush):
  Unknown CMake command "build_ush".


-- Configuring incomplete, errors occurred!
See also "/home/andrewh/Source/microshell/examples/demo_linux/CMakeFiles/CMakeOutput.log".

```

Please advise

**Comment by marcinbor85** [comment]
Hi.
You have to use top-level CMakeLists.txt.
There is a some additional includes, which provide necessary macros and functions needed to build example apps.
Regards.

**Comment by andrewtholt** [comment]
Hi,

I tried again:

pwd is :
/home/andrewh/Source/microshell/Build

cmake ..

***@***.***:Build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at tests/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    /home/andrewh/Source/microshell/tests/Unity/src/unity.c


CMake Error at tests/CMakeLists.txt:5 (add_library):
  No SOURCES given to target: unity


CMake Generate step failed.  Build files cannot be regenerated correctly.


and

pwd:
/home/andrewh/Source/microshell

cmake .

Same result


BTW Unity is an empty directory

Regards,
Andrew

**Comment by andrew-playbrush** [comment]
Fixed.  I needed to get the submodule

This did it:

```
git submodule update --init --recursive
```
