### ISSUE TITLE
[Bug] using ush_print multiple times successively only prints the last command issued

### ISSUE THREAD

**Issue by cosmikwolf** [marcinbor85/microshell#8]
Pretty self explanatory, using ush_print multiple times successively only prints the last command issued.

**Comment by marcinbor85** [comment]
It's not a bug, it's a feature :)
Real printing doesn't take place in the ush_print.
This is only a non-blocking "request" to print something without queuing anything (or only 1 request queue size).
Printing multiple data in one response need implement fsm or big buffer on the application side.

**Comment by cosmikwolf** [comment]
I get it now! I did not realize it was a whole FSM built in. 
It took me a bit, but I figured it out! Some documentation or hints on how to use the FSM in the readme would have made things more clear, but I was able to figure it out after staring at it for a while :D
